/* ============================================================
   Danyi Wang — main.js
   Modules: works filter, lightbox, mobile nav, scroll-aware header,
            fade-in observer, enquiry form

   Language switching used to live here: it swapped textContent from
   data-en / data-cn attributes and remembered the choice in
   localStorage. It is gone. English and Chinese are now separate
   pages under /en/ and /zh/, generated by build.py, and the switch in
   the header is an ordinary link between them.
   ============================================================ */

(function () {
  'use strict';

  /* ── 1. Works Filter ────────────────────────────────────── */
  function initFilter() {
    const bar = document.querySelector('.filter-bar');
    if (!bar) return;

    const buttons = bar.querySelectorAll('.filter-btn');
    const cards   = document.querySelectorAll('.artwork-card[data-category]');

    buttons.forEach(function (btn) {
      btn.addEventListener('click', function () {
        // Active state
        buttons.forEach(function (b) { b.classList.remove('active'); });
        btn.classList.add('active');

        const filter = btn.dataset.filter;

        cards.forEach(function (card) {
          if (filter === 'all' || card.dataset.category === filter) {
            card.classList.remove('hidden');
          } else {
            card.classList.add('hidden');
          }
        });
      });
    });
  }

  /* ── 3. Lightbox ────────────────────────────────────────── */
  let lightboxItems = [];
  let lightboxIndex = 0;

  function buildLightboxItems() {
    lightboxItems = Array.from(
      document.querySelectorAll('.artwork-card[data-src]')
    );
  }

  function openLightbox(index) {
    const lb = document.getElementById('lightbox');
    if (!lb) return;

    lightboxIndex = index;
    const item = lightboxItems[index];
    if (!item) return;

    const img   = lb.querySelector('.lightbox__img');
    const title = lb.querySelector('.lightbox__title');
    const meta  = lb.querySelector('.lightbox__meta');

    // Read the caption off the card as rendered, so the lightbox is in
    // whichever language the page is. The data-* attributes are English
    // only and are kept as a fallback for cards without a caption block.
    const cardTitle = item.querySelector('.artwork-card__title');
    const cardMeta  = item.querySelector('.artwork-card__meta');

    const titleText = cardTitle ? cardTitle.textContent.trim()
                                : (item.dataset.title || '');
    let metaText;
    if (cardMeta) {
      metaText = cardMeta.textContent.trim();
    } else {
      const parts = [];
      if (item.dataset.medium) parts.push(item.dataset.medium);
      if (item.dataset.year)   parts.push(item.dataset.year);
      metaText = parts.join(' · ');
    }

    img.src = item.dataset.src;
    img.alt = titleText;

    if (title) title.textContent = titleText;
    if (meta)  meta.textContent  = metaText;

    lb.classList.add('open');
    document.body.style.overflow = 'hidden';
  }

  function closeLightbox() {
    const lb = document.getElementById('lightbox');
    if (!lb) return;
    lb.classList.remove('open');
    document.body.style.overflow = '';
  }

  function navigateLightbox(dir) {
    const visible = lightboxItems.filter(function (item) {
      return !item.classList.contains('hidden');
    });
    const currentVisible = visible.indexOf(lightboxItems[lightboxIndex]);
    const nextVisible    = (currentVisible + dir + visible.length) % visible.length;
    const nextItem       = visible[nextVisible];
    lightboxIndex        = lightboxItems.indexOf(nextItem);
    openLightbox(lightboxIndex);
  }

  function initLightbox() {
    buildLightboxItems();

    // Open on card click
    lightboxItems.forEach(function (item, index) {
      item.addEventListener('click', function () {
        openLightbox(index);
      });
    });

    const lb = document.getElementById('lightbox');
    if (!lb) return;

    // Close button
    const closeBtn = lb.querySelector('.lightbox__close');
    if (closeBtn) closeBtn.addEventListener('click', closeLightbox);

    // Nav buttons
    const prevBtn = lb.querySelector('.lightbox__prev');
    const nextBtn = lb.querySelector('.lightbox__next');
    if (prevBtn) prevBtn.addEventListener('click', function () { navigateLightbox(-1); });
    if (nextBtn) nextBtn.addEventListener('click', function () { navigateLightbox(1); });

    // Click backdrop to close
    lb.addEventListener('click', function (e) {
      if (e.target === lb) closeLightbox();
    });

    // Keyboard navigation
    document.addEventListener('keydown', function (e) {
      if (!lb.classList.contains('open')) return;
      if (e.key === 'Escape')     closeLightbox();
      if (e.key === 'ArrowLeft')  navigateLightbox(-1);
      if (e.key === 'ArrowRight') navigateLightbox(1);
    });
  }

  /* ── 4. Mobile nav ──────────────────────────────────────── */
  function initMobileNav() {
    const hamburger = document.querySelector('.nav-hamburger');
    const drawer    = document.querySelector('.nav-drawer');
    if (!hamburger || !drawer) return;

    hamburger.addEventListener('click', function () {
      const open = drawer.classList.toggle('open');
      hamburger.setAttribute('aria-expanded', open);
    });

    // Close on outside click
    document.addEventListener('click', function (e) {
      if (!drawer.contains(e.target) && !hamburger.contains(e.target)) {
        drawer.classList.remove('open');
        hamburger.setAttribute('aria-expanded', 'false');
      }
    });

    // Close on nav link click
    drawer.querySelectorAll('a').forEach(function (link) {
      link.addEventListener('click', function () {
        drawer.classList.remove('open');
      });
    });
  }

  /* ── 5. Scroll-aware header ─────────────────────────────── */
  function initScrollHeader() {
    const header = document.querySelector('.site-header');
    if (!header) return;

    function update() {
      header.classList.toggle('scrolled', window.scrollY > 60);
    }

    window.addEventListener('scroll', update, { passive: true });
    update();
  }

  /* ── 6. Fade-in on scroll ───────────────────────────────── */
  function initFadeIn() {
    const els = document.querySelectorAll('.fade-up');
    if (!els.length) return;

    if ('IntersectionObserver' in window) {
      const obs = new IntersectionObserver(function (entries) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add('visible');
            obs.unobserve(entry.target);
          }
        });
      }, { threshold: 0.12 });

      els.forEach(function (el) { obs.observe(el); });
    } else {
      // Fallback: just make them visible
      els.forEach(function (el) { el.classList.add('visible'); });
    }
  }

  /* ── 7a. Guard against an unconfigured form endpoint ────── */
  /* Until a Formspree form ID is filled in, submitting would land the
     visitor on a 404 — worse than having no form. Hide it and show the
     email address instead. Delete this once the action is real. */
  function initFormGuard() {
    const form = document.querySelector('.enquiry-form');
    if (!form) return;
    if (!/REPLACE_WITH_FORM_ID/.test(form.getAttribute('action') || '')) return;

    form.hidden = true;
    const fallback = document.getElementById('form-fallback');
    if (fallback) fallback.hidden = false;
  }

  /* ── 7b. Enquiry form confirmation ──────────────────────── */
  /* Formspree redirects back here with ?sent=1 after a successful post. */
  function initFormSuccess() {
    if (!/[?&]sent=1(&|$)/.test(window.location.search)) return;

    const box = document.getElementById('form-success');
    const form = document.querySelector('.enquiry-form');
    if (box) {
      box.hidden = false;
      box.setAttribute('role', 'status');
    }
    if (form) form.reset();

    // Drop the query string so a refresh doesn't re-show the message.
    if (window.history.replaceState) {
      window.history.replaceState({}, '', window.location.pathname);
    }
    if (box) box.scrollIntoView({ block: 'center' });
  }

  /* ── Init all ───────────────────────────────────────────── */
  document.addEventListener('DOMContentLoaded', function () {
    initFilter();
    initLightbox();
    initMobileNav();
    initScrollHeader();
    initFadeIn();
    initFormGuard();
    initFormSuccess();
  });

})();
